---
- hosts: machines                                     
  tasks:                                 
  - name: synchronize the /data/ folder to each host              
    synchronize:
      src: /data/            
      dest: /data/
      delete: yes   # delete the files that are not found in srs folder
      recursive: yes



