---
- hosts: machines                                     
  tasks:                                 
  - name: synchronize the clean folder /data/ in the control machine to each host              
    synchronize:
      src: /data/            
      dest: /data/
      delete: yes
      recursive: yes

